### ISSUE TITLE
Deactivate per Environment in _ss_environment.php

### ISSUE THREAD

**Issue by asecondwill** [kinglozzer/silverstripe-tinypng#7]
Is there a good way to deactivate this per environment?  I'd rather it wasn't running and using up (or worse, giving warnings about) quota on staging.

**Comment by lozcalver** [comment]
I didn’t think about that when I built this, sorry 😅.

If your staging server is in “live” mode, you could set an invalid API key and it should just silently fail and fall back to the uncompressed image.

Otherwise, I would probably try adding my own extension which overrides the `.Compressed` method... something along the lines of:

```yml
---
Except:
  Environment: live
After: 'tinypngconfig' # May need to be Before:... I can never remember how the ordering works
---
Image:
  extensions:
    - FakeTinyPngImageExtension
```

```php
<?php

class FakeTinyPngImageExtension extends TinyPngImageExtension
{
    public function Compressed()
    {
        $this->owner->setShouldCompress(false); // false, not true
        return $this->owner->getFormattedImage('CompressedImage');
    }

    public function generateCompressedImage(Image_Backend $backend)
    {
        return $backend;
    }
}
```
